service: perna-app

provider:
  name: google
  stage: dev
  region: ${self:custom.regions.${self:provider.stage}}
  project: perna-app
  credentials: ~/.gcloud/keyfile.json
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE: ${self:service}
    PERNA_TOPIC: perna-topic-${self:provider.stage}
    DB_NAME: ${self:service}-${self:provider.stage}
    CALCULATE_ROUTE: CALCULATE_ROUTE_${self:provider.stage}
    MONGO_URL:  ${self:custom.MONGO_URL.${self:provider.stage}}
    GOOGLE_API_URL: ${self:custom.GOOGLE_URL.${self:provider.stage}}
    GOOGLE_API_CREDENTIAL: ${self:custom.GOOGLE_CREDENTIAL.${self:provider.stage}}

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements/${self:provider.stage}.txt
  serverless-offline:
    port: 1337
  regions:
    prd: us-central1
    hml: us-central1
    dev: us-central1
    test: us-central1
  GOOGLE_URL: 
    dev: 'https://maps.googleapis.com/maps/api'
    prd: 'https://maps.googleapis.com/maps/api'
    hml: 'https://maps.googleapis.com/maps/api'
  GOOGLE_CREDENTIAL: 
    dev: 'AIzaSyA0c4Mw7rRAiJxiTQwu6eJcoroBeWWa06w'
    prd: 'AIzaSyA0c4Mw7rRAiJxiTQwu6eJcoroBeWWa06w'
    hml: 'AIzaSyA0c4Mw7rRAiJxiTQwu6eJcoroBeWWa06w'
  MONGO_URL:
    dev: 'mongodb+srv://root:pernaApp00@pernaapp-c7hs8.mongodb.net/test?retryWrites=true&w=majority'
    prd: 'mongodb+srv://root:pernaApp00@pernaapp-c7hs8.mongodb.net/test?retryWrites=true&w=majority'
    hml: 'mongodb+srv://root:pernaApp00@pernaapp-c7hs8.mongodb.net/test?retryWrites=true&w=majority'

plugins:
  - serverless-google-cloudfunctions
  - serverless-python-requirements
  - serverless-pseudo-parameters

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  startRouteCalculation:
    handler: startRouteCalculation
    events:
      - http: startRouteCalculation
  insertAskedPoint:
    handler: insertAskedPoint
    events:
      - http: insertAskedPoint
  getRoutes:
    memorySize: 512
    timeout: 540s
    runtime: python37
    handler: getRoutes
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/perna-topic-${self:provider.stage}'
