service: perna-app

provider:
  name: google
  stage: dev
  region: ${self:custom.regions.${self:provider.stage}}
  project: perna-app
  credentials: .gcloud/keyfile.json
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE: ${self:service}
    PERNA_TOPIC: perna-topic-${self:provider.stage}
    DB_NAME: ${self:service}-${self:provider.stage}
    CALCULATE_ROUTE: CALCULATE_ROUTE_${self:provider.stage}
    GOOGLE_API_URL: ${self:custom.GOOGLE_URL.${self:provider.stage}}
    GOOGLE_API_CREDENTIAL: ${self:custom.GOOGLE_CREDENTIAL.${self:provider.stage}}
    FIREBASE_CONFIG: ./src/config/config.json

functions: ${file(ymls/functions.yml)}
custom: ${file(ymls/custom.yml)}

plugins:
  - serverless-google-cloudfunctions
  - serverless-pseudo-parameters

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**