service: perna-app

provider:
  name: google
  runtime: nodejs10
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.REGIONS.${self:provider.stage}}
  project: ${self:custom.PROJECT_ID.${self:provider.stage}}
  credentials: .gcloud/keyfile.json
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    PROJECT: ${self:provider.project}
    SERVICE: ${self:service}
    PERNA_QUEUE: perna-queue-${self:provider.stage}
    INTEL_URL:  ${self:custom.INTEL_URL.${self:provider.stage}}
    CALCULATE_ROUTE: CALCULATE_ROUTE_${self:provider.stage}
    GOOGLE_API_URL: ${self:custom.GOOGLE_URL.${self:provider.stage}}
    STRIPE_SECRET_KEY_VERSION_NAME: ${self:custom.STRIPE_SECRET_KEY_VERSION_NAME.${self:provider.stage}}
    FIREBASE_CONFIG: ./src/config/config.json

functions: ${file(ymls/functions.yml)}
custom: ${file(ymls/custom.yml)}

plugins:
  - serverless-google-cloudfunctions
  - serverless-google-cronjobs

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**