service: perna-app

provider:
  name: aws
  stage: dev
  timeout: 30
  region: ${self:custom.regions.${self:provider.stage}}
  versionFunctions: false
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE: ${self:service}
    DB_NAME: ${self:service}-${self:provider.stage}
    CALCULATE_ROUTE: CALCULATE_ROUTE_${self:provider.stage}
    MONGO_URL:  ${self:custom.MONGO_URL.${self:provider.stage}}
    GOOGLE_API_URL: ${self:custom.GOOGLE_URL.${self:provider.stage}}
    GOOGLE_API_CREDENTIAL: ${self:custom.GOOGLE_CREDENTIAL.${self:provider.stage}}

custom:
  pythonRequirements:
    fileName: requirements/${self:provider.stage}.txt
  serverless-offline:
    port: 1337
  regions:
    prd: us-east-1
    hml: us-east-1
    dev: us-east-1
    test: us-east-1
  GOOGLE_URL: 
    dev: 'https://maps.googleapis.com/maps/api'
    prd: 'https://maps.googleapis.com/maps/api'
    hml: 'https://maps.googleapis.com/maps/api'
  GOOGLE_CREDENTIAL: 
    dev: 'AIzaSyA0c4Mw7rRAiJxiTQwu6eJcoroBeWWa06w'
    prd: 'AIzaSyA0c4Mw7rRAiJxiTQwu6eJcoroBeWWa06w'
    hml: 'AIzaSyA0c4Mw7rRAiJxiTQwu6eJcoroBeWWa06w'
  MONGO_URL:
    dev: 'mongodb+srv://root:pernaApp00@pernaapp-c7hs8.mongodb.net/test?retryWrites=true&w=majority'
    prd: 'mongodb+srv://root:pernaApp00@pernaapp-c7hs8.mongodb.net/test?retryWrites=true&w=majority'
    hml: 'mongodb+srv://root:pernaApp00@pernaapp-c7hs8.mongodb.net/test?retryWrites=true&w=majority'

resources:
  Resources:
    CalculateRouteQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: CALCULATE_ROUTE_${self:provider.stage}
        VisibilityTimeout: 900

functions:
  startRouteCalculation:
    runtime: nodejs10.x
    handler: index.startRouteCalculation
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:*
        Resource: '*'
    events:
      - http:
          path: startRouteCalculation
          method: post
  getRoutes:
    runtime: python3.6
    handler: index.getRoutes
    timeout: 900
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:*
        Resource: '*'
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:CALCULATE_ROUTE_${self:provider.stage}
          batchSize: 10
plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

package:
  individually: true
  exclude:
    - database/**
    - package-lock.json
    - .gitignore
    - .vscode/**