'use strict';

module.exports = {
  GOOGLE_MAP_API: {
    STATUS_OK: 'OK',
  },
  APP_ENGINE: {
    SERVICE: 'default',
  },
  MESSAGES: {
    NO_COMPANY: 'No company whit this id',
    THERE_ARE_EXPEDIENTS: 'There are still unresolved expedients',
    NO_BANK: 'No bank whit this id',
    NO_USER: 'No user whit this email',
    UNAUTHORIZED_USER: 'unauthorized user',
    TOKEN_REQUIRED: 'Token is required',
    USER_DOESNT_EXISITS: 'There is no user whit this email',
    USER_EXISITS: 'There is a user whit this email',
    MUST_BE_PROVIDER: 'Must be a provider',
    INVALID_START_END: 'Start time must be less than end time',
    NULL_ASKED_POINT: 'Order cannot be null',
    INVALID_QUEUE: 'There cannot be equal days in the queue',
    MUST_BE_TWO_PROVIDERS: 'There must be two providers involved',
    NO_DEVICE: 'No devices registered',
    NO_EVENT: 'Not recognized event',
    NOT_VALID_BANK: 'Not valid bank',
    NOT_VALID_COMPANY: 'Not valid company',
    NOT_VALID_EVENT: 'Not valid event',
  },
  ENCODED_NAMES: {
    SEPARETOR: '<{*_-_*}>',
  },
  COLLECTION_NAMES: {
    BANK: 'bank',
    COMPANY: 'company',
    AGENT: 'agent',
    ASKED_POINT: 'askedPoint',
    USER: 'user',
  },
  EVENT_TYPE: {
    AGENT: 'agent',
    ASKED_POINT: 'askedPoint',
  },
  ASKED_POINT_FIELDS: {
    EMAIL: 'email',
    DATE: 'date',
    QUEUE: 'queue',
    ASKED_START_AT: 'askedStartAt',
    ASKED_END_AT: 'askedEndAt',
  },
  AGENT_FIELDS: {
    EMAIL: 'email',
    DATE: 'date',
    QUEUE: 'queue',
    ASKED_START_AT: 'askedStartAt',
    ASKED_END_AT: 'askedEndAt',
  },
  COMPANY_FIELDS: {
    MANAGER: 'manager',
  },
  USER_FIELDS: {
    EMAIL: 'email',
    IS_PROVIDER: 'isProvider',
  },
  RETURN_MESSAGES: {
    SUCCESS: 'success',
  },
  MODEL_FIELDS: {
    AGENT: [
      'companyId',
      'askedStartAt',
      'askedEndAt',
      'places',
      'friendlyGarage',
      'garage',
      'date',
      'email',
      'region',
      'staticMap',
    ],
    BANK_ACCOUNT: [
      'accountHolderName',
      'accountHolderType',
      'bankName',
      'countryCode',
      'email',
      'currency',
      'accountNumber',
      'routingNumber',
    ],
    COMPANY: [
      'employees',
      'manager',
      'businessType',
      'address',
      'companyName',
      'companyNumber',
      'structure',
      'phone',
      'country',
      'currency',
    ],
    ASKED_POINT: [
      'friendlyDestiny',
      'destiny',
      'friendlyOrigin',
      'origin',
      'date',
      'email',
      'region',
      'staticMap',
    ],
  },
};
