version: '3'

services:
  mongo:
    image: mongo
    container_name: odc-jec-admin-db
    command: [--auth]
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "Pitaang00"
